[build]
publish = "public/"
command = "hugo"

[context.production]
publish = "public/"
command = "hugo"

[[redirects]]

[redirects.headers]
X-From = "Netlify"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"