[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"
HUFO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
HUGO_VERSION = "0.80.0"

[context.deploy-preview.environment]
HUGO_VERSION = "0.80.0"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"

[[plugins]]
package = "netlify-plugin-submit-sitemap"

[plugins.inputs]
baseUrl = "https://richardbanks.net"
sitemapPath = "/sitemap.xml"

providers = [
  "google",
  "bing",
  "yandex"
]
